#!/bin/bash
# create-client-package
# usage: ./create-client-package build-dir version-string architecture

# check usage
if [ $# -lt 3 ]
then
echo usage: $0 build-dir version-string architecture
exit 1
fi

# directories
ROOT_DIR=$1
INFO_DIR=$ROOT_DIR/DEBIAN
BINARY_DIR=$ROOT_DIR/usr/bin
MAN1_DIR=$ROOT_DIR/usr/share/man/man1

# source files
MAN1_PAGES=minecontrol.1

# destination files
CONTROL_FILE=$INFO_DIR/control

# create directories if they do not exist
if [ ! -d $ROOT_DIR ]
then
mkdir $ROOT_DIR
fi
if [ ! -d $INFO_DIR ]
then
mkdir $INFO_DIR
fi
if [ ! -d $BINARY_DIR ]
then
mkdir -p $BINARY_DIR
fi
if [ ! -d $MAN1_DIR ]
then
mkdir -p $MAN1_DIR
fi

# make the control file
echo "Package: minecontrol" > $CONTROL_FILE
echo Version: $2 >> $CONTROL_FILE
echo "Maintainer: Roger Gee <rpg11a@acu.edu>" >> $CONTROL_FILE
echo "Description: A minecontrol client program" >> $CONTROL_FILE
echo Architecture: $3 >> $CONTROL_FILE
echo "Depends: libc6, libstdc++6, libssl1.0.0, libncurses5" >> $CONTROL_FILE

# copy all files to destinations
cp minecontrol $BINARY_DIR
cp $MAN1_PAGES $MAN1_DIR

# compress man pages
gzip -9 $MAN1_DIR/*.1

# create .deb package
dpkg-deb --build $ROOT_DIR .
