#!/bin/bash
# create-lib-package
# usage: ./create-lib-package build-dir version-string architecture

# check usage
if [ $# -lt 3 ]
then
echo usage: $0 build-dir version-string architecture
exit 1
fi

# directories
ROOT_DIR=$1
INFO_DIR=$ROOT_DIR/DEBIAN
LIB_DIR=$ROOT_DIR/usr/lib

# source files
AUTH_LIBRARY_REALNAME=libminecontrol-api.so.1.0.0
AUTH_LIBRARY_SONAME=libminecontrol-api.so.1
AUTH_LIBRARY_LINKNAME=libminecontrol-api.so
AUTH_LIBRARY=auth/$AUTH_LIBRARY_REALNAME

# destination files
CONTROL_FILE=$INFO_DIR/control
POSTINST_FILE=$INFO_DIR/postinst
POSTRM_FILE=$INFO_DIR/postrm

# create directories if they do not exist
if [ ! -d $ROOT_DIR ]
then
mkdir $ROOT_DIR
fi
if [ ! -d $INFO_DIR ]
then
mkdir $INFO_DIR
fi
if [ ! -d $LIB_DIR ]
then
mkdir -p $LIB_DIR
fi

# make the control file
echo "Package: libminecontrol-api1" > $CONTROL_FILE
echo Version: $2 >> $CONTROL_FILE
echo "Maintainer: Roger Gee <rpg11a@acu.edu>" >> $CONTROL_FILE
echo "Description: Minecontrol authority API shared library" >> $CONTROL_FILE
echo Architecture: $3 >> $CONTROL_FILE
echo "Depends: libc6" >> $CONTROL_FILE

# copy files to destination
cp postinst-lib $POSTINST_FILE
cp postrm-lib $POSTRM_FILE
cp $AUTH_LIBRARY $LIB_DIR

# create the .deb package
dpkg-deb --build $ROOT_DIR .
