#!/bin/bash
# create-dev-package
# usage: ./create-dev-package build-dir version-string architecture

# check usage
if [ $# -lt 3 ]
then
echo usage: $0 build-dir version-string architecture
exit 1
fi

# directories
ROOT_DIR=$1
INFO_DIR=$ROOT_DIR/DEBIAN
INCLUDE_DIR=$ROOT_DIR/usr/include/minecontrol
LIB_DIR=$ROOT_DIR/usr/lib

# source files
HEADERS="auth/minecontrol-api.h auth/tree.h"
AUTH_LIBRARY_SONAME=libminecontrol-api.so.1
AUTH_LIBRARY_LINKNAME=libminecontrol-api.so

# destination files
CONTROL_FILE=$INFO_DIR/control

# create directories if they do not exist
if [ ! -d $ROOT_DIR ]
then
mkdir $ROOT_DIR
fi
if [ ! -d $INFO_DIR ]
then
mkdir $INFO_DIR
fi
if [ ! -d $INCLUDE_DIR ]
then 
mkdir -p $INCLUDE_DIR
fi
if [ ! -d $LIB_DIR ]
then
mkdir -p $LIB_DIR
fi

# make the control file
echo "Package: libminecontrol-api-dev" > $CONTROL_FILE
echo Version: $2 >> $CONTROL_FILE
echo "Maintainer: Roger Gee <rpg11a@acu.edu>" >> $CONTROL_FILE
echo "Description: Minecontrol authority API development headers" >> $CONTROL_FILE
echo Architecture: $3 >> $CONTROL_FILE
echo "Depends: libc6, libminecontrol-api1" >> $CONTROL_FILE

# copy files to destination
cp $HEADERS $INCLUDE_DIR

# create link name to SONAME
ln -s /usr/lib/$AUTH_LIBRARY_SONAME $LIB_DIR/$AUTH_LIBRARY_LINKNAME

# create the .deb package
dpkg-deb --build $ROOT_DIR .
